[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
cargo-util-schemas = { version = "0.7.1" }
serde = "1.0.217"
toml = "0.8.20"
semver = "1.0.25"
crc32fast = "1.4.2"
serde_json = "1.0.138"
